### PR TITLE
add base32 

### PR DESCRIPTION
**Pull request by flyq**

### CODE REVIEW

**Comment by kritzcreek** [comment]
CI is failing because you haven't tagged the version you're specifying on your library yet. Happy to merge after CI passes.

**Comment by flyq** [comment]
Thanks for reminding, I release the version in https://github.com/flyq/motoko-base32/releases/tag/v0.1.0 , but the CI is failing too, anything I need do more?

**Comment by flyq** [comment]
ok, I think I have fixed it.

**Review by kritzcreek — APPROVED** [review]
LGTM

**Comment by kritzcreek** [comment]
Available starting with `mo-0.6.6-20210809`

**Pull request merged**
