### PR TITLE
Bump `moc` to 0.7.6

### PR DESCRIPTION
**Pull request by rvanasa**

### CODE REVIEW

**Review by ggreif — APPROVED** [review]
LGTM!

**Comment by rvanasa** [comment]
@ggrief, it looks like something is up with the repository permissions. I could open a JIRA ticket if that would be helpful in regards to time zone.

**Comment by ggreif** [comment]
(it's @ggreif :-)
Which permissions? I am not an admin here.

**Comment by rvanasa** [comment]
Whoops; sorry about the typo! Thanks.

Since you're part of `dfinity/dx`, you should be able to approve PRs in this repository, right?

**Review by ggreif — APPROVED** [review]
LGTM!

**Comment by ggreif** [comment]
My vote is not good enough here :-(

**Pull request merged**
